// =============================================================================
// GENERATED POLICY DATA — Mexican materias (jurisdicción MX, sistema civil).
//
// Which engines may run, which finding modules may persist, which motion
// families may be drafted, which report sections render and which terms are
// forbidden in prose — all keyed by the canonical Mexican materia
// (MexicanCaseType). There is exactly one such table set in the codebase;
// src/lib/jurisdiction/mexico.ts is the only module that reads it.
// =============================================================================
import type { MexicanCaseType } from "./mexico-types";

export const MX_SECTIONS: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  civil: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  mercantil: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  familiar: ["opportunities", "perspectives", "recommendations", "risk", "scorecard", "strategy_synthesis", "theories"],
  laboral: [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  administrativo: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  fiscal: [
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  amparo: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  constitucional: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  electoral: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  agrario: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  ambiental: [
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
  inmobiliario: ["opportunities", "perspectives", "recommendations", "risk", "scorecard", "transaction_center"],
  migratorio: [
    "constitutional",
    "cross_exam",
    "discovery",
    "opportunities",
    "perspectives",
    "recommendations",
    "risk",
    "scorecard",
    "strategy_synthesis",
    "theories",
  ],
};

export const MX_TABS: Record<MexicanCaseType, readonly string[]> = {
  penal: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  civil: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  mercantil: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  familiar: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  laboral: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  administrativo: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  fiscal: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  amparo: ["opportunities", "perspectives", "scorecard", "strategy", "theories"],
  constitucional: ["opportunities", "perspectives", "scorecard", "strategy", "theories"],
  electoral: ["opportunities", "perspectives", "scorecard", "strategy", "theories"],
  agrario: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  ambiental: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
  inmobiliario: ["opportunities", "scorecard", "transaction_center"],
  migratorio: ["opportunities", "perspectives", "scorecard", "strategy", "theories", "trial", "witnesses"],
};

// NOTE (2026-08-04): `trial_prep` was removed entirely from CANONICAL_STAGES
// on 2026-08-02 — it no longer exists as a runnable stage for any materia.
// Every prior entry here listed it anyway; that stale reference is dropped
// below (it never caused a functional bug, since a non-existent stage can
// never be scheduled, but it was misleading policy data).
export const MX_ENGINES: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "agent:search_warrant_arrest_legality",
    "agent:forensic_digital_evidence_analysis",
    "agent:reasonable_doubt_defense_theory",
    "agent:sentencing_analysis",
    "agent:appeal_opportunity_detection",
  ],
  civil: [
    "cross_examination",
    "agent:contract_analysis_ambiguity",
    "agent:liability_damages_assessment",
    "agent:payment_insurance_analysis",
    "agent:statute_of_limitations_analysis",
    "agent:settlement_opportunity_analyzer",
  ],
  mercantil: [
    "cross_examination",
    "agent:corporate_governance_shareholder_rights",
    "agent:commercial_contract_intelligence",
    "agent:financial_fraud_commercial_risk",
    "agent:bankruptcy_concurso_review",
  ],
  familiar: [
    // FIX: familiar was the only litigated (non-purely-documentary) materia
    // in this entire table missing cross_examination — confirmed by
    // comparing against every other entry, including laboral (a similarly
    // "mostly written" materia), which already has it. Familiar audiencias
    // (custodia, alimentos, violencia familiar) routinely involve live
    // witness testimony — family members, peritos en psicología/trabajo
    // social — and the materia's own EXCLUDED_STAGES (mx-pipeline.ts) does
    // NOT exclude the witness stage, confirming testimony is already
    // considered relevant here. Without this engine, no cross-examination
    // prep was ever generated for a materia where it's routinely needed.
    "cross_examination",
    "agent:custody_best_interest_analysis",
    "agent:child_support_calculation",
    "agent:domestic_violence_assessment",
  ],
  laboral: [
    "agent:lft_compliance_review",
    "agent:payroll_overtime_imss_audit",
    "agent:wrongful_termination_analysis",
    "agent:union_discrimination_review",
  ],
  administrativo: [
    "cross_examination",
    "agent:administrative_due_process_review",
    "agent:authority_competence_notification_review",
    "agent:administrative_nullity_analysis",
  ],
  fiscal: [
    "cross_examination",
    "agent:sat_audit_review",
    "agent:cfdi_accounting_tax_validation",
    "agent:prodecon_opportunity_detection",
  ],
  amparo: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "agent:standing_procedencia",
    "agent:suspension_analysis",
    "agent:conventionality_pro_persona",
    "agent:constitutional_rights_mapping",
    "agent:authority_notification_validation",
    "agent:international_human_rights_analysis",
  ],
  constitucional: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "agent:standing_procedencia",
    "agent:suspension_analysis",
    "agent:conventionality_pro_persona",
    "agent:constitutional_rights_mapping",
    "agent:authority_notification_validation",
    "agent:international_human_rights_analysis",
    "agent:constitutional_controversy_analysis",
  ],
  electoral: [
    "chain_of_custody",
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "agent:ine_documentation_candidate_eligibility",
    "agent:campaign_finance_review",
    "agent:vote_counting_chain_of_custody",
    "agent:political_violence_gender_parity",
    "agent:electoral_nullity_analysis",
  ],
  agrario: [
    "cross_examination",
    "agent:ran_record_certificate_review",
    "agent:ejido_assembly_analysis",
    "agent:communal_land_indigenous_rights",
    "agent:boundary_possession_analysis",
    "agent:agrarian_jurisdiction_restitution",
  ],
  ambiental: [
    "constitutional_compliance",
    "cross_examination",
    "agent:mia_impact_assessment_review",
    "agent:profepa_asea_compliance_review",
    "agent:conagua_water_rights_review",
    "agent:pollution_remediation_analysis",
    "agent:protected_species_areas_review",
  ],
  inmobiliario: ["property_verification", "closing_readiness_scoring"],
  migratorio: [
    "constitutional_compliance",
    "cross_examination",
    "procedural_violations",
    "agent:immigration_eligibility_analysis",
    "agent:immigration_deadline_continuity",
    "agent:refugee_non_refoulement_analysis",
    "agent:nationality_naturalization_analysis",
    "agent:immigration_due_process_remedies",
    "agent:child_vulnerability_protection",
  ],
};

export const MX_FINDING_MODULES: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "appeal_opportunity_detection",
    "cadena_de_custodia",
    "carpeta_de_investigacion",
    "datos_de_prueba",
    "debido_proceso",
    "defensa_adecuada",
    "defraudacion_fiscal",
    "detencion_ilegal",
    "exclusion_de_prueba_ilicita",
    "forensic_digital_evidence_analysis",
    "individualizacion_sancion",
    "medidas_cautelares",
    "presuncion_de_inocencia",
    "prision_preventiva_oficiosa",
    "procedural",
    "reasonable_doubt_defense_theory",
    "reparacion_del_dano",
    "salidas_alternas",
    "search_warrant_arrest_legality",
    "sentencing_analysis",
    "teoria_del_caso",
    "vinculacion_a_proceso",
  ],
  civil: [
    "accion_plenaria_de_posesion",
    "accion_reivindicatoria",
    "arrendamiento",
    "causalidad",
    "civil_procedure_mx",
    "contract_analysis_ambiguity",
    "contrato",
    "liability_damages_assessment",
    "payment_insurance_analysis",
    "settlement_opportunity_analyzer",
    "statute_of_limitations_analysis",
    "copropiedad",
    "cumplimiento_forzoso",
    "dano_material",
    "dano_moral",
    "danos_y_perjuicios",
    "desocupacion_arrendamiento",
    "enriquecimiento_ilegitimo",
    "escritura_publica",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "fianza",
    "gestion_de_negocios",
    "gravamen",
    "hecho_ilicito",
    "hipoteca",
    "incumplimiento_contractual",
    "interdicto",
    "lesion",
    "mora",
    "negligencia_profesional",
    "nulidad_absoluta",
    "nulidad_relativa",
    "obligacion_solidaria",
    "ofrecimiento_de_pruebas",
    "pena_convencional",
    "peritaje",
    "posesion",
    "prescripcion_adquisitiva",
    "prescripcion_negativa",
    "registro_publico_de_la_propiedad",
    "rescision_contractual",
    "responsabilidad_civil_objetiva",
    "responsabilidad_civil_subjetiva",
    "riesgo_creado",
    "saneamiento_para_el_caso_de_eviccion",
    "servidumbre",
    "simulacion_de_actos",
    "usufructo",
    "vicios_del_consentimiento",
    "vicios_ocultos",
  ],
  // REBUILT 2026-07-29: this list previously contained ~345 entries of
  // U.S. federal securities, banking, and IP doctrine (10b_5, dodd_frank,
  // sarbanes_oxley, hmda, tila, respa, glba, pslra, cfpb, ecoa, lanham_act,
  // dmca, markman, howey_test, wells_notice, etc.) — none of which are
  // Mexican commercial law. Rebuilt from the actual governing framework:
  // Código de Comercio (juicio ejecutivo/oral mercantil), Ley General de
  // Títulos y Operaciones de Crédito (pagaré, letra de cambio, aval),
  // Ley General de Sociedades Mercantiles (asamblea, consejo de
  // administración, fusión/escisión), Ley de Concursos Mercantiles,
  // Ley del Mercado de Valores, Ley de Instituciones de Crédito, Ley para
  // Regular las Instituciones de Tecnología Financiera (Ley Fintech),
  // Ley Federal de Competencia Económica, Ley Federal de Protección a la
  // Propiedad Industrial, Ley Federal de Protección al Consumidor, and the
  // Ley Federal para la Prevención e Identificación de Operaciones con
  // Recursos de Procedencia Ilícita. This is a representative core
  // taxonomy, not a claim of exhaustive coverage — extend it as real case
  // material surfaces gaps, the same way the original (mis-scoped) list
  // grew over time.
  mercantil: [
    "bankruptcy_concurso_review",
    "commercial_contract_intelligence",
    "corporate_governance_shareholder_rights",
    "financial_fraud_commercial_risk",
    "pagare",
    "letra_de_cambio",
    "cheque",
    "aval",
    "endoso",
    "protesto",
    "accion_cambiaria",
    "caducidad_cambiaria",
    "prescripcion_cambiaria",
    "obligacion_cambiaria",
    "certificado_de_deposito",
    "bono_de_prenda",
    "obligacion_subordinada",
    "contrato_mercantil",
    "compraventa_mercantil",
    "contrato_de_suministro",
    "contrato_de_comision_mercantil",
    "contrato_de_deposito_mercantil",
    "contrato_de_transporte",
    "contrato_de_seguro",
    "contrato_de_fianza",
    "factoraje_financiero",
    "arrendamiento_financiero",
    "fideicomiso",
    "fideicomiso_de_garantia",
    "contrato_de_apertura_de_credito",
    "contrato_de_credito_simple",
    "contrato_de_credito_en_cuenta_corriente",
    "sociedad_anonima",
    "sociedad_de_responsabilidad_limitada",
    "sociedad_por_acciones_simplificada",
    "asamblea_de_accionistas",
    "asamblea_general_ordinaria",
    "asamblea_general_extraordinaria",
    "consejo_de_administracion",
    "administrador_unico",
    "capital_social",
    "partes_sociales",
    "comisario",
    "fusion",
    "escision",
    "liquidacion_societaria",
    "disolucion_societaria",
    "responsabilidad_de_administradores",
    "accion_de_responsabilidad",
    "estatutos_sociales",
    "acta_de_asamblea",
    "juicio_ejecutivo_mercantil",
    "juicio_oral_mercantil",
    "via_ejecutiva",
    "via_ordinaria_mercantil",
    "titulo_ejecutivo",
    "embargo_mercantil",
    "excepciones_procesales_mercantiles",
    "recurso_de_apelacion_mercantil",
    "prueba_pericial_mercantil",
    "auto_de_exequendo",
    "requerimiento_de_pago",
    "diligencia_de_embargo",
    "tercero_excluyente",
    "concurso_mercantil",
    "conciliacion_concursal",
    "quiebra",
    "sindico",
    "visitador",
    "conciliador",
    "masa_concursal",
    "reconocimiento_de_creditos",
    "declaracion_de_concurso_mercantil",
    "garantia_mobiliaria",
    "prenda_mercantil",
    "hipoteca_mercantil",
    "credito_mercantil",
    "interes_moratorio",
    "interes_ordinario",
    "usura",
    "tasa_de_interes_usuraria",
    "oferta_publica_de_valores",
    "emisora",
    "bolsa_mexicana_de_valores",
    "comision_nacional_bancaria_y_de_valores",
    "condusef",
    "banxico",
    "institucion_de_credito",
    "institucion_de_banca_multiple",
    "sofom",
    "sofipo",
    "ley_fintech",
    "institucion_de_tecnologia_financiera",
    "activo_virtual",
    "cuenta_de_fondos_de_pago_electronico",
    "competencia_economica",
    "cofece",
    "practica_monopolica",
    "concentracion_prohibida",
    "poder_sustancial_de_mercado",
    "propiedad_industrial",
    "marca",
    "patente",
    "nombre_comercial",
    "infraccion_administrativa",
    "impi",
    "aviso_comercial",
    "arbitraje_comercial",
    "clausula_compromisoria",
    "laudo_arbitral",
    "camara_de_comercio",
    "reconocimiento_y_ejecucion_de_laudo",
    "proteccion_al_consumidor",
    "profeco",
    "publicidad_enganosa",
    "clausula_abusiva",
    "operaciones_con_recursos_de_procedencia_ilicita",
    "unidad_de_inteligencia_financiera",
    "uif",
    "aviso_ante_la_uif",
  ],
  familiar: [
    "adopcion",
    "albacea",
    "alimentos",
    "capacidad_juridica",
    "child_support_calculation",
    "concubinato",
    "convenio_regulador",
    "convivencia_supervisada",
    "custody_best_interest_analysis",
    "dependencia_economica",
    "divorcio_incausado",
    "domestic_violence_assessment",
    "divorcio_necesario",
    "filiacion",
    "guarda_y_custodia",
    "interes_superior_del_menor",
    "inventario_y_avaluo",
    "juicio_sucesorio_intestamentario",
    "juicio_sucesorio_testamentario",
    "nulidad_de_matrimonio",
    "nulidad_de_testamento",
    "patria_potestad",
    "pension_alimenticia",
    "perdida_de_patria_potestad",
    "procuraduria_de_proteccion_nnna",
    "prueba_pericial_psicologica",
    "reconocimiento_de_paternidad",
    "regimen_patrimonial",
    "separacion_de_bienes",
    "sociedad_conyugal",
    "sucesion_legitima",
    "testamento_publico_abierto",
    "tutela",
    "violencia_familiar",
  ],
  laboral: [
    "aguinaldo",
    "antiguedad",
    "conciliacion_prejudicial",
    "contrato_colectivo_de_trabajo",
    "contrato_individual_de_trabajo",
    "despido_injustificado",
    "discriminacion_laboral",
    "emplazamiento_a_huelga",
    "enfermedad_de_trabajo",
    "finiquito",
    "hostigamiento_y_acoso_laboral",
    "horas_extra",
    "lft_compliance_review",
    "payroll_overtime_imss_audit",
    "union_discrimination_review",
    "wrongful_termination_analysis",
    "imss",
    "indemnizacion_constitucional",
    "infonavit",
    "jornada_laboral",
    "nom_035_riesgos_psicosociales",
    "nulidad_de_renuncia",
    "ofrecimiento_de_trabajo",
    "prima_de_antiguedad",
    "prima_vacacional",
    "ptu_reparto_de_utilidades",
    "reinstalacion",
    "rescision_de_la_relacion_laboral",
    "riesgo_de_trabajo",
    "salarios_caidos",
    "sindicato",
    "subordinacion",
    "tabla_de_valuacion_de_incapacidades",
    "trabajador_de_confianza",
  ],
  administrativo: [
    "acto_administrativo",
    "administrative_due_process_review",
    "administrative_nullity_analysis",
    "authority_competence_notification_review",
    "caducidad_del_procedimiento",
    "civil_procedure_mx",
    "competencia_de_la_autoridad",
    "contrato",
    "cumplimiento_forzoso",
    "dano_material",
    "danos_y_perjuicios",
    "debida_fundamentacion_y_motivacion",
    "derecho_de_audiencia",
    "desvio_de_poder",
    "excepciones_dilatorias",
    "excepciones_perentorias",
    "garantia_del_interes_fiscal",
    "incumplimiento_contractual",
    "juicio_de_nulidad",
    "licencia_o_permiso",
    "negativa_ficta",
    "notificacion_ilegal",
    "nulidad_absoluta",
    "nulidad_lisa_y_llana",
    "nulidad_para_efectos",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "prescripcion_negativa",
    "procedimiento_administrativo_sancionador",
    "recurso_de_revision_administrativo",
    "responsabilidad_administrativa_de_servidores_publicos",
    "responsabilidad_patrimonial_del_estado",
    "silencio_administrativo",
    "suspension_del_acto",
    "visita_de_verificacion",
  ],
  fiscal: [
    "actualizacion_y_recargos",
    "aclaracion_articulo_69b",
    "cancelacion_de_sellos_digitales",
    "caducidad_de_facultades_de_comprobacion",
    "cfdi_accounting_tax_validation",
    "credito_fiscal",
    "deduccion_improcedente",
    "prodecon_opportunity_detection",
    "sat_audit_review",
    "determinacion_presuntiva",
    "devolucion_de_saldo_a_favor",
    "discrepancia_fiscal",
    "embargo_precautorio",
    "facultades_de_comprobacion",
    "garantia_del_interes_fiscal",
    "juicio_contencioso_administrativo",
    "multa_fiscal",
    "negativa_ficta_fiscal",
    "opinion_de_cumplimiento_32d",
    "prescripcion_del_credito_fiscal",
    "procedimiento_administrativo_de_ejecucion",
    "recurso_de_revocacion",
    "revision_de_gabinete",
    "revision_electronica",
    "visita_domiciliaria",
  ],
  amparo: [
    "acto_reclamado",
    "authority_notification_validation",
    "autoridad_responsable",
    "conceptos_de_violacion",
    "constitutional",
    "constitutional_rights_mapping",
    "control_de_convencionalidad",
    "conventionality_pro_persona",
    "cumplimiento_de_sentencia_de_amparo",
    "debido_proceso",
    "derechos_fundamentales",
    "detencion_arbitraria",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "international_human_rights_analysis",
    "principio_pro_persona",
    "procedencia",
    "procedural",
    "standing_procedencia",
    "suplencia_de_la_queja",
    "suspension",
    "suspension_analysis",
    "suspension_de_plano",
    "tercero_interesado",
    "tortura",
    "uso_excesivo_de_la_fuerza",
    "violacion_derechos_humanos",
  ],
  // 2026-08-04: previously a byte-for-byte copy of amparo's list. Left the
  // shared amparo-style tokens (acto_reclamado, interes_juridico, etc. — a
  // controversia constitucional / acción de inconstitucionalidad case can
  // still legitimately raise them) but added the doctrine specific to
  // constitutional-controversy adjudication that amparo doesn't have: which
  // used to mean a genuine controversia constitucional case had nowhere to
  // record an invasión de competencias or proportionality-test finding.
  constitucional: [
    "acto_reclamado",
    "authority_notification_validation",
    "autoridad_responsable",
    "bloque_de_constitucionalidad",
    "conceptos_de_violacion",
    "constitutional",
    "constitutional_controversy_analysis",
    "constitutional_rights_mapping",
    "control_de_convencionalidad",
    "control_difuso",
    "conventionality_pro_persona",
    "cumplimiento_de_sentencia_de_amparo",
    "debido_proceso",
    "derechos_fundamentales",
    "detencion_arbitraria",
    "improcedencia",
    "interes_juridico",
    "interes_legitimo",
    "international_human_rights_analysis",
    "invasion_de_competencias",
    "principio_de_division_de_poderes",
    "principio_pro_persona",
    "procedencia",
    "procedural",
    "standing_procedencia",
    "suplencia_de_la_queja",
    "suspension",
    "suspension_analysis",
    "suspension_de_plano",
    "tercero_interesado",
    "test_de_igualdad",
    "test_de_proporcionalidad",
    "tortura",
    "uso_excesivo_de_la_fuerza",
    "violacion_derechos_humanos",
  ],
  electoral: [
    "campaign_finance_review",
    "civil_procedure_mx",
    "constitutional",
    "electoral_nullity_analysis",
    "fiscalizacion_de_gastos_de_campana",
    "ine_documentation_candidate_eligibility",
    "libertad_de_expresion_electoral",
    "nulidad_de_eleccion",
    "political_violence_gender_parity",
    "nulidad_absoluta",
    "nulidad_relativa",
    "ofrecimiento_de_pruebas",
    "paridad_de_genero",
    "procedimiento_especial_sancionador",
    "procedural",
    "propaganda_electoral",
    "recuento_de_votos",
    "registro_de_candidatura",
    "violencia_politica_en_razon_de_genero",
    "vote_counting_chain_of_custody",
  ],
  // 2026-08-04: previously a copy of civil's contract/tort taxonomy — no
  // agrarian doctrine at all (no RAN, ejido, deslinde, or restitución
  // concepts). Rebuilt from the actual governing framework, Ley Agraria.
  agrario: [
    "agrarian_jurisdiction_restitution",
    "asamblea_ejidal",
    "bienes_comunales",
    "boundary_possession_analysis",
    "certificado_parcelario",
    "colindancias",
    "comisariado_ejidal",
    "communal_land_indigenous_rights",
    "consulta_previa_indigena",
    "deslinde",
    "despojo",
    "ejido_assembly_analysis",
    "identidad_de_superficie",
    "nucleo_agrario",
    "ofrecimiento_de_pruebas",
    "posesion_agraria",
    "prescripcion_negativa",
    "procedural",
    "ran_record_certificate_review",
    "restitucion_de_tierras",
    "tierras_de_uso_comun",
  ],
  ambiental: [
    "autorizacion_cambio_uso_suelo",
    "clausura_profepa",
    "conagua_water_rights_review",
    "concesion_agua_conagua",
    "dano_ambiental",
    "denuncia_popular_ambiental",
    "mia_impact_assessment_review",
    "pollution_remediation_analysis",
    "profepa_asea_compliance_review",
    "protected_species_areas_review",
    "descarga_aguas_residuales",
    "emisiones_contaminantes",
    "estudio_riesgo_ambiental",
    "gases_efecto_invernadero",
    "licencia_ambiental_unica",
    "manifestacion_impacto_ambiental",
    "medidas_de_seguridad_profepa",
    "nom_ambiental_incumplimiento",
    "permiso_forestal_conafor",
    "procedimiento_administrativo_profepa",
    "proteccion_areas_naturales_conanp",
    "recurso_de_revision_ambiental",
    "regulacion_industria_hidrocarburos_asea",
    "remediacion_ambiental",
    "residuos_peligrosos",
    "responsabilidad_ambiental_objetiva",
  ],
  inmobiliario: [
    "adeudo_agua",
    "adeudo_cfe",
    "adeudo_cuotas_de_condominio",
    "adeudo_predial",
    "cancelacion_hipoteca",
    "catastro",
    "closing_readiness_scoring",
    "cuenta_predial",
    "discrepancia_medidas",
    "discrepancia_propietario",
    "property_verification",
    "documento_faltante",
    "documento_vencido",
    "escritura_publica",
    "fideicomiso_zona_restringida",
    "firma_faltante",
    "folio_real",
    "gravamen",
    "hipoteca_vigente",
    "levantamiento_topografico",
    "libertad_de_gravamen",
    "permiso_construccion",
    "poder_notarial",
    "uso_de_suelo",
  ],
  migratorio: [
    "immigration_eligibility_analysis",
    "immigration_deadline_continuity",
    "refugee_non_refoulement_analysis",
    "nationality_naturalization_analysis",
    "immigration_due_process_remedies",
    "child_vulnerability_protection",
    "condicion_de_estancia",
    "continuidad_migratoria",
    "documento_migratorio",
    "familia_y_filiacion",
    "empleador_y_actividad_remunerada",
    "verificacion_migratoria",
    "detencion_migratoria",
    "deportacion_y_retorno",
    "refugio",
    "proteccion_complementaria",
    "principio_de_no_devolucion",
    "interes_superior_de_la_ninez",
    "debido_proceso_administrativo",
    "competencia_y_notificacion",
    "remedio_administrativo",
    "juicio_de_nulidad_tfja",
    "amparo_migratorio",
    "nacionalidad",
    "naturalizacion",
    "vigencia_fuente_legal",
  ],
};

export const MX_MOTION_TYPES: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "acuerdo_reparatorio",
    "amparo_indirecto_penal",
    "impugnacion_medidas_cautelares",
    "procedimiento_abreviado",
    "recurso_de_apelacion",
    "solicitud_de_no_vinculacion",
    "suspension_condicional",
  ],
  civil: [
    "alegatos",
    "amparo_directo_civil",
    "amparo_indirecto_civil",
    "contestacion_demanda",
    "cumplimiento_forzoso_de_contrato",
    "demanda_civil",
    "desahogo_de_vista",
    "excepciones_procesales",
    "incidente_de_liquidacion",
    "incidente_falta_personalidad",
    "incidente_nulidad_actuaciones",
    "interdicto",
    "juicio_ejecutivo_civil",
    "medidas_provisionales",
    "objecion_de_documentos",
    "ofrecimiento_pruebas",
    "providencias_precautorias",
    "reconvencion",
    "recurso_de_apelacion_civil",
    "recurso_de_revocacion_civil",
  ],
  mercantil: [
    "accion_de_responsabilidad_de_administradores",
    "alegatos",
    "amparo_directo_mercantil",
    "amparo_indirecto_mercantil",
    "arbitraje_comercial",
    "concurso_mercantil",
    "contestacion_demanda_mercantil",
    "convenio_judicial",
    "demanda_mercantil",
    "ejecucion_de_sentencia",
    "embargo_precautorio_mercantil",
    "excepciones_y_defensas",
    "incidente_de_liquidacion_de_intereses",
    "incidente_nulidad_actuaciones",
    "juicio_ejecutivo_mercantil",
    "juicio_oral_mercantil",
    "nulidad_de_asamblea",
    "objecion_de_documentos",
    "ofrecimiento_pruebas",
    "providencias_precautorias_mercantiles",
    "recurso_de_apelacion_mercantil",
    "recurso_de_revocacion_mercantil",
  ],
  familiar: [
    "alegatos",
    "amparo_directo_familiar",
    "amparo_indirecto_familiar",
    "convenio_regulador",
    "demanda_de_divorcio",
    "guarda_y_custodia",
    "incidente_de_convivencias",
    "incidente_de_modificacion_de_pension",
    "inventario_y_avaluo",
    "juicio_sucesorio_intestamentario",
    "juicio_sucesorio_testamentario",
    "medidas_provisionales_familiares",
    "nombramiento_de_albacea",
    "nulidad_de_testamento",
    "ofrecimiento_pruebas",
    "orden_de_proteccion",
    "pension_alimenticia_provisional",
    "perdida_de_patria_potestad",
    "recurso_de_apelacion_familiar",
  ],
  laboral: [
    "alegatos",
    "amparo_directo_laboral",
    "amparo_indirecto_laboral",
    "contestacion_demanda_laboral",
    "demanda_laboral",
    "ejecucion_de_laudo",
    "emplazamiento_a_huelga",
    "incidente_de_liquidacion",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_de_trabajo",
    "ofrecimiento_pruebas",
    "recurso_de_reclamacion",
    "solicitud_de_conciliacion_prejudicial",
  ],
  administrativo: [
    "alegatos",
    "ampliacion_de_demanda",
    "amparo_directo_administrativo",
    "amparo_indirecto_administrativo",
    "demanda_contencioso_administrativa",
    "incidente_de_incompetencia",
    "juicio_de_nulidad",
    "medidas_cautelares_administrativas",
    "ofrecimiento_pruebas",
    "queja_por_incumplimiento",
    "recurso_de_revision_administrativo",
    "recurso_de_revision_fiscal",
    "suspension_del_acto_impugnado",
  ],
  fiscal: [
    "aclaracion_articulo_69b",
    "acuerdo_conclusivo_prodecon",
    "alegatos",
    "ampliacion_de_demanda",
    "amparo_directo_fiscal",
    "amparo_indirecto_fiscal",
    "garantia_del_interes_fiscal",
    "juicio_contencioso_administrativo",
    "juicio_de_resolucion_exclusiva_de_fondo",
    "juicio_en_la_via_sumaria",
    "ofrecimiento_pruebas",
    "recurso_de_revocacion",
    "solicitud_de_devolucion",
    "suspension_del_procedimiento_administrativo_de_ejecucion",
  ],
  amparo: [
    "alegatos",
    "ampliacion_de_demanda_de_amparo",
    "demanda_de_amparo",
    "denuncia_de_repeticion_del_acto_reclamado",
    "incidente_de_cumplimiento_sustituto",
    "incidente_de_inejecucion_de_sentencia",
    "incidente_de_suspension",
    "ofrecimiento_pruebas",
    "recurso_de_queja",
    "recurso_de_reclamacion",
    "recurso_de_revision",
    "suspension_de_plano",
  ],
  // 2026-08-04: previously a byte-for-byte copy of amparo's motion list
  // (demanda_de_amparo, incidente_de_suspensión...) — legally the wrong
  // vehicle for a controversia constitucional / acción de
  // inconstitucionalidad, which is a distinct action under art. 105 CPEUM
  // with its own procedural instruments, not an amparo. A genuinely
  // classified "constitucional" case could previously only draft amparo
  // filings — the wrong procedural vía for that action entirely.
  constitucional: [
    "alegatos_controversia_constitucional",
    "ampliacion_de_demanda_controversia_constitucional",
    "contestacion_de_demanda_controversia_constitucional",
    "demanda_de_accion_de_inconstitucionalidad",
    "demanda_de_controversia_constitucional",
    "informe_de_ley_controversia_constitucional",
    "ofrecimiento_pruebas",
    "opinion_de_la_procuraduria_general",
    "promocion_de_incidente_de_suspension_controversia",
    "recurso_de_reclamacion_controversia",
    "recurso_de_reclamacion_accion_inconstitucionalidad",
  ],
  electoral: [
    "alegatos",
    "juicio_de_inconformidad",
    "juicio_de_revision_constitucional_electoral",
    "juicio_para_la_proteccion_de_los_derechos_politico_electorales",
    "medidas_cautelares_electorales",
    "ofrecimiento_pruebas",
    "procedimiento_especial_sancionador",
    "queja_ante_el_ine",
    "recurso_de_apelacion_electoral",
    "recurso_de_reconsideracion",
  ],
  // 2026-08-04: previously civil's litigation motion list (reconvención,
  // providencias precautorias...) — an agrarian matter is filed before a
  // Tribunal Unitario Agrario under the Ley Agraria, not a civil court.
  agrario: [
    "alegatos_agrarios",
    "amparo_directo_agrario",
    "amparo_indirecto_agrario",
    "contestacion_demanda_agraria",
    "demanda_agraria",
    "demanda_de_restitucion_de_tierras",
    "incidente_nulidad_actuaciones",
    "ofrecimiento_pruebas",
    "recurso_de_revision_agrario",
    "solicitud_de_deslinde",
  ],
  ambiental: [
    "amparo_indirecto_ambiental",
    "denuncia_popular",
    "impugnacion_negativa_concesion_conagua",
    "impugnacion_permiso_forestal_conafor",
    "incidente_suspension_profepa",
    "juicio_de_nulidad_ambiental",
    "medidas_cautelares_ambientales",
    "ofrecimiento_pruebas",
    "recurso_de_revision",
  ],
  // Deliberately empty: a closing has no motions. If a real estate matter
  // ever needs one, it has become a dispute — i.e. civil, not inmobiliario.
  inmobiliario: [],
  migratorio: [
    "recurso_administrativo_migratorio",
    "juicio_de_nulidad_tfja_migratorio",
    "amparo_indirecto_migratorio",
    "amparo_directo_migratorio",
    "incidente_de_suspension_migratoria",
    "solicitud_de_libertad_o_alternativa_a_detencion",
    "impugnacion_negativa_comar",
    "impugnacion_negativa_naturalizacion",
    "queja_cndh",
    "ofrecimiento_pruebas",
  ],
};

export const MX_BLOCKED_TERMS: Record<MexicanCaseType, readonly string[]> = {
  penal: [
    "child custody",
    "custody dispute",
    "discrimination claim",
    "district attorney",
    "felony",
    "grand jury",
    "miranda",
    "misdemeanor",
    "payroll records",
    "plea bargain",
    "spousal support",
    "title vii",
    "wrongful termination",
  ],
  civil: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "medical malpractice",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "standard of care",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  mercantil: [
    "brady violation",
    "child custody",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "standard of care",
    "title vii",
    "wrongful termination",
  ],
  familiar: [
    "brady violation",
    "criminal procedure",
    "eeoc",
    "grand jury",
    "indictment",
    "medical malpractice",
    "miranda",
    "search and seizure",
    "sentencing",
    "standard of care",
    "title vii",
    "wrongful termination",
  ],
  laboral: ["brady violation", "child custody", "criminal procedure", "indictment", "miranda", "spousal support"],
  administrativo: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  fiscal: [
    "child custody",
    "criminal procedure",
    "grand jury",
    "indictment",
    "miranda",
    "search and seizure",
    "sentencing",
    "spousal support",
    "title vii",
    "wrongful termination",
  ],
  amparo: [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support",
  ],
  constitucional: [
    "child custody",
    "contrato mercantil",
    "despido injustificado",
    "divorce",
    "divorcio",
    "herencia",
    "payroll records",
    "pensión alimenticia",
    "spousal support",
  ],
  electoral: [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "divorce",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "payroll records",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  agrario: [
    "brady violation",
    "celotex",
    "child custody",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  ambiental: [
    "brady violation",
    "celotex",
    "child custody",
    "criminal procedure",
    "deposition",
    "discovery request",
    "eeoc",
    "grand jury",
    "hearsay",
    "indictment",
    "iqbal",
    "miranda",
    "motion to dismiss",
    "punitive damages",
    "rule 12(b)(6)",
    "rule 56",
    "search and seizure",
    "sentencing",
    "specific performance of unique goods",
    "spousal support",
    "subpoena",
    "summary judgment",
    "title vii",
    "tortious interference",
    "twombly",
    "wrongful termination",
  ],
  inmobiliario: [
    "cross examination",
    "custody dispute",
    "grand jury",
    "hearsay",
    "indictment",
    "jury trial",
    "miranda",
    "motion to dismiss",
    "plea bargain",
    "punitive damages",
    "sentencing",
    "spousal support",
    "subpoena",
    "trial strategy",
    "wrongful termination",
  ],
  migratorio: [
    "uscis",
    "ice immigration",
    "green card",
    "removal court",
    "i-130",
    "i-485",
    "adjustment of status",
    "american asylum court",
    "u.s. visa classification",
    "jury",
    "grand jury",
    "plea bargain",
  ],
};

export const MX_FORBIDDEN_REPORT_FIELDS: Record<MexicanCaseType, readonly string[]> = {
  penal: [],
  civil: ["constitutional_issues", "constitutional_issues_struct"],
  mercantil: ["constitutional_issues", "constitutional_issues_struct"],
  familiar: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
  laboral: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
  administrativo: ["constitutional_issues", "constitutional_issues_struct"],
  fiscal: ["constitutional_issues", "constitutional_issues_struct"],
  amparo: [],
  constitucional: [],
  electoral: [],
  agrario: ["constitutional_issues", "constitutional_issues_struct"],
  ambiental: [],
  inmobiliario: ["constitutional_issues", "constitutional_issues_struct", "cross_examination"],
  migratorio: [
    "jury_instructions",
    "sentencing_guidelines",
    "plea_bargain",
    "uscis_form",
    "us_visa_classification",
  ],
};
