// Talk-to-Case "Push to Report" — reviews the chat exchange against the
// EXISTING case intelligence, lets the attorney see and approve the
// resulting patch set BEFORE anything is written, then applies it and
// regenerates only the report. Two explicit steps (preview, then apply)
// rather than one atomic call: the case-revision architecture requires a
// Proposal -> Validation -> Dependency Analysis -> User Approval -> Apply
// chain, not an AI silently rewriting case_findings on its own judgment.
// See useAddEvidenceAndRerun for the separate, genuinely-new-evidence full
// rerun flow this deliberately never touches.
import { useCallback, useRef, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import {
  previewCaseChatCorrections,
  pushCaseChatCorrectionsToReport,
  finalizeReportChangeLog,
} from "@/lib/cases.functions";

export type CorrectionAction =
  | "keep"
  | "amend"
  | "remove"
  | "merge"
  | "create"
  | "dispute_evidence";

/** Mirrors chat-patch.server.ts's FindingPatch — kept as a local client-side
 *  type (this codebase's existing pattern, see ChatMsg/Doc in
 *  CaseChatPanel.tsx) rather than importing across the client/server
 *  boundary from a *.server.ts module. Passed through opaquely by the
 *  client: generated by previewCaseChatCorrections, round-tripped verbatim
 *  to pushCaseChatCorrectionsToReport, never constructed or edited here. */
export type CorrectionPatch = {
  action: CorrectionAction;
  finding_ids: string[];
  reason: string;
  quote: string;
  source_document_id: string | null;
  confidence: number;
  new_title?: string;
  new_description?: string;
  new_category?: string;
  new_severity?: "critical" | "high" | "medium" | "low" | "info";
  disputed_doc_id?: string;
  dispute_status?: "disputed" | "superseded" | "withdrawn";
};

export type CorrectionImpact = {
  dependentFindingIds: string[];
  scoreAffected: boolean;
  affectedOpportunityIds: string[];
  affectedCitationCount: number;
};

/** Self-audit (Phase B, §7): NYRAVA recognizing a finding resembles a
 *  category it has a verified recurring weakness in. Informational only —
 *  covers EXISTING active findings, not just ones this exchange proposes
 *  correcting, and never implies the finding is wrong. */
export type SelfAuditNotice = {
  findingId: string;
  findingTitle: string;
  patternId: string;
  errorType: string;
  tier: "candidate" | "strong" | "significant";
  recommendedAction:
    | "require_additional_evidence"
    | "require_second_source"
    | "require_authority_verification"
    | "require_procedural_posture_verification"
    | "lower_confidence"
    | "send_to_critic"
    | "require_human_review";
  reason: string;
};

export type CorrectionPreview = {
  patches: CorrectionPatch[];
  ungrounded: number;
  impact: CorrectionImpact | null;
  currentFindings: Array<{ id: string; title: string; category: string; severity: string }>;
  selfAuditNotices: SelfAuditNotice[];
};

export type ApplySuccessResult = {
  ok: true;
  nextVersion: number | null;
  patchCount: number;
  rescored: boolean;
  /** Report citations still referencing a finding this correction just
   *  superseded — flagged for review, not auto-rewritten. See
   *  chat-patch.server.ts's findStaleCitations. */
  staleCitationCount: number;
};

/** A patch's target finding was superseded by something else (an earlier
 *  correction, a rerun) between when this proposal was previewed and when
 *  the attorney clicked Apply — nothing was written. The server already
 *  regenerated a fresh proposal against the case's CURRENT findings (the
 *  same thing clicking "Review correction" again would produce); the
 *  caller should show that instead of failing with nothing to act on. */
export type ApplyStaleResult = {
  ok: false;
  reason: "stale_target";
  staleFindingIds: string[];
  refreshedPreview: CorrectionPreview;
};

export type ApplyResult = ApplySuccessResult | ApplyStaleResult;

export function usePushChatCorrectionsToReport(caseId: string) {
  const previewFn = useServerFn(previewCaseChatCorrections);
  const pushFn = useServerFn(pushCaseChatCorrectionsToReport);
  const finalizeFn = useServerFn(finalizeReportChangeLog);

  const [busy, setBusy] = useState(false);
  const [progress, setProgress] = useState("");
  const runningRef = useRef(false);

  const preview = useCallback(
    async (chatMessageId: string): Promise<CorrectionPreview> => {
      if (runningRef.current)
        throw new Error("A report review is already in progress for this case.");
      runningRef.current = true;
      setBusy(true);
      try {
        setProgress("Reviewing existing findings against this exchange…");
        const res = await previewFn({ data: { caseId, chatMessageId } });
        return {
          patches: res.patches as CorrectionPatch[],
          ungrounded: res.ungrounded,
          impact: res.impact,
          currentFindings: res.currentFindings,
          selfAuditNotices: res.selfAuditNotices as SelfAuditNotice[],
        };
      } finally {
        runningRef.current = false;
        setBusy(false);
        setProgress("");
      }
    },
    [caseId, previewFn],
  );

  const apply = useCallback(
    async (chatMessageId: string, patches: CorrectionPatch[]): Promise<ApplyResult> => {
      if (patches.length === 0) throw new Error("No corrections to apply.");
      if (runningRef.current)
        throw new Error("A report update is already in progress for this case.");
      runningRef.current = true;
      setBusy(true);
      try {
        setProgress("Applying the approved correction…");
        const res = await pushFn({ data: { caseId, chatMessageId, patches } });

        if (!res.ok) {
          // A target finding was superseded since this proposal was
          // previewed — nothing was written. The server already
          // regenerated a fresh proposal against the case's current
          // findings; hand it back so the caller can show it instead of
          // failing with no next step.
          return {
            ok: false,
            reason: "stale_target",
            staleFindingIds: res.staleFindingIds,
            refreshedPreview: {
              patches: res.refreshedPreview.patches as CorrectionPatch[],
              ungrounded: res.refreshedPreview.ungrounded,
              impact: res.refreshedPreview.impact,
              currentFindings: res.refreshedPreview.currentFindings,
              selfAuditNotices: res.refreshedPreview.selfAuditNotices as SelfAuditNotice[],
            },
          };
        }

        if (res.nextVersion != null) {
          setProgress("Computing What's Changed…");
          await finalizeFn({ data: { caseId } });
        }

        return {
          ok: true,
          nextVersion: res.nextVersion,
          patchCount: res.applied.filter((o) => o.applied).length,
          rescored: res.rescored,
          staleCitationCount: res.staleCitations.length,
        };
      } finally {
        runningRef.current = false;
        setBusy(false);
        setProgress("");
      }
    },
    [caseId, pushFn, finalizeFn],
  );

  return { preview, apply, busy, progress };
}
