ALTER TABLE public.resource_knowledge_records ALTER COLUMN created_by DROP NOT NULL;

ALTER TABLE public.resource_knowledge_case_actions DROP CONSTRAINT IF EXISTS resource_knowledge_case_actions_action_type_check;
ALTER TABLE public.resource_knowledge_case_actions ADD CONSTRAINT resource_knowledge_case_actions_action_type_check CHECK (action_type = ANY (ARRAY['attach_reference','add_required_form','create_checklist','create_task','find_related_resources','start_referral','share_client_version','ask_talk_to_case','add_to_case_work']));

DELETE FROM public.resource_knowledge_records WHERE org_id IS NULL AND 'nyrava_approved_library' = ANY(population_tags);

INSERT INTO public.resource_knowledge_records
 (org_id,title_es,title_en,summary_es,summary_en,content_es,content_en,knowledge_type,service_categories,state_codes,population_tags,authority,source_url,approval_status,approved_at,effective_at,last_verified_at,review_due_at,audience,language_codes,purpose,when_to_use,applicable_programs,required_steps,official_sources,internal_only)
VALUES
(NULL,'Procedimiento de atención a personas migrantes y solicitantes de refugio','Immigration and refugee intake procedure',
 'Guía operativa para la primera atención de personas migrantes, solicitantes de la condición de refugiado y personas con necesidades de protección internacional.',
 'Operational guidance for first contact with migrants, asylum seekers and people with international protection needs.',
 'Verifique situación migratoria declarada, riesgo de retorno y necesidades inmediatas. Documente el relato en las propias palabras de la persona. Informe plazos: la solicitud de la condición de refugiado ante la COMAR debe presentarse, por regla general, dentro de los 30 días hábiles siguientes al ingreso al país; existen excepciones por causa justificada. Nunca asesore sobre el fondo del caso si no es persona abogada: canalice a servicios jurídicos.',
 'Verify declared migration situation, risk on return and immediate needs. Record the account in the person''s own words. Explain deadlines: refugee status applications before COMAR are generally filed within 30 business days of entry, with justified exceptions. Never give substantive legal advice unless you are a lawyer: refer to legal services.',
 'procedure',ARRAY['immigration_refugees','referrals','case_management'],'{}',ARRAY['nyrava_approved_library','migrants','asylum_seekers'],'COMAR / INM','https://www.gob.mx/comar','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Estandarizar la primera atención y evitar la pérdida de plazos de protección internacional.','Al abrir un caso donde la persona declara ser migrante, refugiada o solicitante de asilo.',ARRAY['immigration'],
 '["Registrar identidad, nacionalidad, idioma y fecha aproximada de ingreso.","Detectar necesidades urgentes: salud, alimentación, alojamiento, protección de niñez.","Explicar plazos y alcance del trámite ante COMAR e INM sin ofrecer asesoría jurídica de fondo.","Recabar consentimiento informado antes de compartir información con cualquier institución.","Canalizar a servicios jurídicos y, si aplica, a albergue mediante la Red de Recursos.","Registrar la actuación en el expediente y programar seguimiento."]'::jsonb,
 '[{"title":"COMAR - Comisión Mexicana de Ayuda a Refugiados","url":"https://www.gob.mx/comar"},{"title":"Instituto Nacional de Migración","url":"https://www.gob.mx/inm"}]'::jsonb,true),

(NULL,'Cuándo canalizar a servicios jurídicos','When to refer to legal services',
 'Criterios para identificar cuándo un caso requiere asistencia jurídica y cómo canalizarlo.',
 'Criteria for identifying when a case requires legal assistance and how to refer it.',
 'El personal de atención no debe interpretar normas ni redactar promociones. Canalice cuando exista: riesgo de detención o deportación, procedimiento administrativo o judicial en curso, plazos legales corriendo, necesidad de representación de niñez, violencia con posible denuncia penal, o solicitud de reconocimiento de la condición de refugiado.',
 'Care staff must not interpret statutes or draft legal filings. Refer when there is: detention or removal risk, an open administrative or judicial procedure, running legal deadlines, a child needing representation, violence with a possible criminal complaint, or a refugee status application.',
 'procedure',ARRAY['legal_services','referrals','case_management'],'{}',ARRAY['nyrava_approved_library'],'Instituto Federal de Defensoría Pública','https://www.gob.mx/defensoriapublica','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Evitar la práctica no autorizada del derecho y asegurar acceso oportuno a defensa.','Cuando se detecte cualquier necesidad legal identificada en la guía.',ARRAY['legal'],
 '["Documentar el hecho y la necesidad jurídica identificada, sin calificarla jurídicamente.","Verificar consentimiento para compartir información con la instancia jurídica.","Buscar en la Red de Recursos la defensoría o clínica jurídica competente.","Crear la canalización y registrar acuse o número de referencia.","Programar seguimiento a 5 días hábiles."]'::jsonb,
 '[{"title":"Instituto Federal de Defensoría Pública","url":"https://www.gob.mx/defensoriapublica"}]'::jsonb,true),

(NULL,'Protocolo de protección de niñas, niños y adolescentes','Child protection safeguarding protocol',
 'Señales de alerta, medidas de protección y ruta de escalamiento ante posible vulneración de derechos de la niñez.',
 'Warning signs, protective measures and escalation route for possible child rights violations.',
 'Toda sospecha razonable de maltrato, abuso, abandono, explotación o niñez no acompañada debe escalarse el mismo día a supervisión y a la Procuraduría de Protección de Niñas, Niños y Adolescentes correspondiente. El interés superior de la niñez rige toda decisión (art. 4 constitucional; Ley General de los Derechos de Niñas, Niños y Adolescentes).',
 'Any reasonable suspicion of abuse, neglect, exploitation or an unaccompanied child must be escalated the same day to supervision and to the competent child protection authority. The best interests of the child govern every decision.',
 'protocol',ARRAY['child_protection','referrals','case_management'],'{}',ARRAY['nyrava_approved_library','children'],'SIPINNA / DIF / Procuraduría de Protección','https://www.gob.mx/sipinna','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Garantizar respuesta inmediata y trazable ante riesgos para la niñez.','Ante cualquier indicio de riesgo o vulneración de derechos de una persona menor de 18 años.',ARRAY['child_protection'],
 '["Asegurar la seguridad inmediata de la niña, niño o adolescente.","Registrar hechos observados de forma objetiva, sin inducir el relato.","Notificar a supervisión el mismo día y dejar constancia de la hora.","Reportar a la Procuraduría de Protección o al DIF competente.","Crear tarea de seguimiento y alerta de revisión a 24 y 72 horas.","Restringir el acceso al expediente conforme al nivel de confidencialidad."]'::jsonb,
 '[{"title":"SIPINNA","url":"https://www.gob.mx/sipinna"},{"title":"SNDIF","url":"https://www.gob.mx/difnacional"}]'::jsonb,true),

(NULL,'Metodología de trabajo social: valoración, plan y notas de caso','Social work practice: assessment, care plan and case notes',
 'Estructura mínima de la valoración social, del plan de atención y de las notas de seguimiento.',
 'Minimum structure for social assessment, care plan and follow-up notes.',
 'La valoración documenta necesidades, factores protectores y riesgos con evidencia observada. El plan de atención define objetivo, acción, responsable, fecha objetivo y resultado esperado. Las notas se registran en las 48 horas siguientes al contacto y describen hechos, no juicios.',
 'The assessment documents needs, protective factors and risks with observed evidence. The care plan sets goal, action, owner, target date and expected outcome. Notes are recorded within 48 hours of contact and describe facts, not opinions.',
 'intake_manual',ARRAY['social_work','case_management'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Unificar la calidad y trazabilidad del expediente social.','En cada apertura de caso y en cada revisión periódica.',ARRAY['social_work'],
 '["Realizar la valoración inicial dentro de los 5 días hábiles de la apertura.","Registrar nivel de riesgo con justificación escrita.","Elaborar plan de atención con al menos un objetivo medible por necesidad.","Documentar cada contacto en nota de caso dentro de 48 horas.","Revisar el plan al menos cada 30 días o al cambiar el riesgo."]'::jsonb,'[]'::jsonb,true),

(NULL,'Valoración y canalización psicosocial','Psychosocial assessment and referral guidance',
 'Criterios de canalización psicosocial y escalamiento en crisis emocional.',
 'Psychosocial referral criteria and escalation in emotional crisis.',
 'Ante ideación suicida, autolesión, desorganización severa o crisis aguda, no deje sola a la persona, escale de inmediato a supervisión y active servicios de emergencia o la Línea de la Vida (800 911 2000). El personal no clínico no realiza diagnóstico.',
 'For suicidal ideation, self-harm, severe disorganization or acute crisis, do not leave the person alone, escalate immediately to supervision and activate emergency services or the national crisis line (800 911 2000). Non-clinical staff do not diagnose.',
 'risk_guidance',ARRAY['psychosocial_services','medical_emergency','referrals'],'{}',ARRAY['nyrava_approved_library'],'Secretaría de Salud - Línea de la Vida','https://www.gob.mx/salud/conadic','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Responder con seguridad ante crisis y canalizar a atención especializada.','Cuando se identifiquen indicadores emocionales de riesgo durante cualquier contacto.',ARRAY['psychosocial'],
 '["Aplicar contención básica y verificar seguridad inmediata.","Escalar a supervisión y registrar la hora de escalamiento.","Activar emergencia o línea de crisis si hay riesgo de vida.","Canalizar a servicio psicológico verificado mediante la Red de Recursos.","Crear alerta de seguimiento a 24 horas."]'::jsonb,
 '[{"title":"Línea de la Vida (800 911 2000)","url":"https://www.gob.mx/salud/conadic"}]'::jsonb,true),

(NULL,'Procedimiento de emergencia médica y activación externa','Medical emergency and external activation procedure',
 'Cuándo se requiere asistencia externa inmediata y cómo documentarla.',
 'When immediate outside assistance is required and how to document it.',
 'Llame al 911 ante pérdida de conciencia, hemorragia, dificultad respiratoria, lesión por violencia reciente, intoxicación o riesgo de vida. En violencia sexual reciente, la atención médica es urgente por plazos de profilaxis; no condicione la atención a la presentación de denuncia (NOM-046-SSA2-2005).',
 'Call 911 for loss of consciousness, bleeding, breathing difficulty, recent violence injury, poisoning or life risk. After recent sexual violence, medical care is urgent due to prophylaxis windows; never condition care on filing a criminal complaint (NOM-046-SSA2-2005).',
 'emergency_procedure',ARRAY['medical_emergency','domestic_violence','referrals'],'{}',ARRAY['nyrava_approved_library'],'Secretaría de Salud - NOM-046-SSA2-2005','https://www.gob.mx/salud','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Evitar demoras en atención de urgencia y dejar constancia de la actuación.','En cualquier situación con riesgo para la vida o la integridad física.',ARRAY['health'],
 '["Llamar al 911 y permanecer con la persona hasta la llegada de auxilio.","Notificar a supervisión y registrar hora de llamada y unidad receptora.","Registrar hechos observados en nota de caso sin diagnóstico clínico.","Canalizar a unidad de salud verificada para seguimiento.","Programar seguimiento a 24 horas."]'::jsonb,
 '[{"title":"NOM-046-SSA2-2005","url":"https://www.gob.mx/salud"}]'::jsonb,true),

(NULL,'Canalización a albergues y alojamiento temporal','Shelter and temporary housing referral guidance',
 'Elegibilidad, documentación y procedimiento para canalizar a albergue.',
 'Eligibility, documentation and procedure for shelter referrals.',
 'Confirme disponibilidad por teléfono antes de trasladar a la persona. Verifique si el albergue admite familias, hombres, niñez no acompañada o personas con discapacidad. No divulgue la ubicación de refugios para víctimas de violencia.',
 'Confirm availability by phone before moving anyone. Check whether the shelter admits families, men, unaccompanied children or people with disabilities. Never disclose the location of violence shelters.',
 'referral_instruction',ARRAY['housing_shelters','referrals','domestic_violence'],'{}',ARRAY['nyrava_approved_library'],'DIF / CONAVIM','https://www.gob.mx/conavim','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Asegurar alojamiento seguro y evitar traslados fallidos.','Cuando la persona carece de alojamiento seguro esa misma noche.',ARRAY['housing'],
 '["Valorar riesgo y composición del grupo familiar.","Confirmar cupo y requisitos por teléfono con el albergue.","Recabar consentimiento para compartir datos con el albergue.","Registrar la canalización con fecha, hora y persona contactada.","Confirmar el ingreso efectivo y registrar el resultado."]'::jsonb,
 '[{"title":"CONAVIM - Refugios","url":"https://www.gob.mx/conavim"}]'::jsonb,true),

(NULL,'Identificación y seguridad ante trata de personas','Human trafficking identification and safety guidance',
 'Indicadores de identificación, medidas de seguridad y ruta de escalamiento.',
 'Identification indicators, safety measures and escalation route.',
 'Indicadores: control de documentos por terceros, deuda impuesta, restricción de movimiento, jornada extrema, aislamiento, temor a hablar frente a acompañantes. Entreviste siempre a solas, nunca en presencia del posible tratante. Escale a supervisión y a la fiscalía especializada; existe la línea 800 5533 000.',
 'Indicators: third parties holding documents, imposed debt, movement restriction, extreme hours, isolation, fear of speaking in front of companions. Always interview alone, never with the possible trafficker present. Escalate to supervision and the specialized prosecutor; national line 800 5533 000.',
 'protocol',ARRAY['human_trafficking','child_protection','referrals'],'{}',ARRAY['nyrava_approved_library'],'FEVIMTRA / CNDH','https://www.gob.mx/fgr','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Identificar posibles víctimas sin poner en riesgo su seguridad.','Ante cualquier indicador de explotación laboral o sexual o de control coercitivo.',ARRAY['protection'],
 '["Separar a la persona de acompañantes y entrevistar en espacio privado.","No confrontar ni alertar a posibles responsables.","Registrar indicadores observados de forma objetiva.","Escalar el mismo día a supervisión y a la autoridad especializada.","Canalizar a refugio y atención a víctimas.","Restringir el expediente al personal estrictamente necesario."]'::jsonb,
 '[{"title":"FGR - FEVIMTRA","url":"https://www.gob.mx/fgr"},{"title":"CEAV","url":"https://www.gob.mx/ceav"}]'::jsonb,true),

(NULL,'Valoración de seguridad y canalización en violencia familiar','Domestic violence safety assessment and referral guide',
 'Valoración de riesgo, plan de seguridad, documentación y escalamiento.',
 'Risk assessment, safety planning, documentation and escalation.',
 'Valore riesgo letal: amenazas de muerte, armas en casa, estrangulamiento previo, separación reciente, acoso persistente, violencia durante embarazo. Ante riesgo alto, active plan de seguridad, informe sobre órdenes de protección y canalice a refugio y a la instancia de atención a mujeres. Línea nacional 800 108 4053.',
 'Assess lethality risk: death threats, weapons at home, prior strangulation, recent separation, persistent stalking, violence during pregnancy. For high risk, activate the safety plan, inform about protection orders, and refer to shelter and the women''s assistance authority. National line 800 108 4053.',
 'risk_guidance',ARRAY['domestic_violence','housing_shelters','legal_services','referrals'],'{}',ARRAY['nyrava_approved_library','women'],'CONAVIM / INMUJERES','https://www.gob.mx/conavim','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Reducir riesgo letal y conectar con protección y servicios especializados.','Cuando la persona reporte violencia por parte de pareja o familiar.',ARRAY['gbv'],
 '["Entrevistar a solas y verificar seguridad para hablar.","Aplicar la valoración de riesgo y registrar el nivel resultante.","Elaborar plan de seguridad con la persona usuaria.","Informar sobre órdenes de protección sin dar asesoría jurídica de fondo.","Canalizar a refugio, servicios jurídicos y atención médica según el riesgo.","Programar seguimiento a 24-72 horas y crear alerta."]'::jsonb,
 '[{"title":"CONAVIM","url":"https://www.gob.mx/conavim"},{"title":"INMUJERES","url":"https://www.gob.mx/inmujeres"}]'::jsonb,true),

(NULL,'Consentimiento informado y compartición de información','Informed consent and information sharing procedure',
 'Reglas para recabar consentimiento y compartir información del caso.',
 'Rules for obtaining consent and sharing case information.',
 'Recabe consentimiento informado por escrito antes de compartir datos con cualquier tercero, indicando finalidad, destinatarios, información autorizada y vigencia. Los datos de salud, origen étnico, situación migratoria y violencia son datos sensibles conforme a la LFPDPPP. Sin consentimiento vigente solo procede compartir ante riesgo inminente para la vida o mandato legal, dejando constancia.',
 'Obtain written informed consent before sharing data with any third party, stating purpose, recipients, authorized information and validity. Health, ethnicity, migration status and violence data are sensitive data under Mexican data protection law. Without valid consent, sharing is only allowed for imminent life risk or legal mandate, and must be recorded.',
 'consent_template',ARRAY['consent_privacy','referrals','case_management'],'{}',ARRAY['nyrava_approved_library'],'LFPDPPP / INAI','https://home.inai.org.mx','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Proteger datos personales sensibles y sustentar cada compartición.','Antes de cualquier canalización, envío de documentos o contacto con instituciones.',ARRAY['compliance'],
 '["Explicar finalidad y alcance en el idioma de la persona usuaria.","Registrar consentimiento con fecha, vigencia e información autorizada.","Compartir únicamente la información autorizada, nunca el expediente completo.","Registrar cada acceso o envío de documentos.","Revocar o actualizar el consentimiento cuando la persona lo solicite."]'::jsonb,
 '[{"title":"INAI","url":"https://home.inai.org.mx"}]'::jsonb,true),

(NULL,'Cómo crear, enviar, documentar y dar seguimiento a una canalización','How to create, send, document and follow up a referral',
 'Ciclo completo de canalización, desde la identificación hasta el cierre.',
 'Full referral cycle, from identification to closure.',
 'Una canalización solo procede con consentimiento vigente y con recurso verificado en la Red de Recursos. Registre acuse, persona receptora y fecha compromiso. Sin respuesta en 5 días hábiles, reintente y escale a supervisión a los 10.',
 'A referral requires valid consent and a verified resource from the Resource Network. Record acknowledgement, receiving contact and commitment date. With no answer in 5 business days, retry, and escalate to supervision at 10.',
 'referral_instruction',ARRAY['referrals','case_management'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Evitar canalizaciones perdidas y documentar resultados.','Cada vez que el caso requiera un servicio externo.',ARRAY['case_management'],
 '["Identificar el servicio requerido a partir del plan de atención.","Verificar consentimiento e información autorizada.","Seleccionar el recurso verificado en la Red de Recursos.","Enviar la canalización y registrar acuse.","Crear tarea de seguimiento a 5 días hábiles.","Registrar el resultado: aceptada, rechazada, sin respuesta o concluida."]'::jsonb,'[]'::jsonb,true),

(NULL,'Procedimiento integral de gestión de casos','End-to-end case-management procedure',
 'Ruta completa: recepción, valoración, plan de atención, canalización, seguimiento y cierre.',
 'Full route: intake, assessment, care plan, referral, follow-up and closure.',
 'Cada etapa tiene un producto documental obligatorio. No se cierra un caso con canalizaciones abiertas, riesgo alto vigente o consentimiento no resuelto. El cierre requiere justificación y revisión de supervisión.',
 'Each stage has a mandatory documentary output. A case cannot be closed with open referrals, active high risk or unresolved consent. Closure requires justification and supervisory review.',
 'procedure',ARRAY['case_management','social_work','referrals'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Homologar el ciclo de vida del caso y sus controles.','Desde la apertura del caso hasta su cierre o transferencia.',ARRAY['case_management'],
 '["Recepción: registrar identidad, motivo y necesidades inmediatas.","Valoración: determinar riesgo y factores protectores con evidencia.","Plan de atención: objetivos, acciones, responsables y fechas.","Canalización: servicios externos con consentimiento y acuse.","Seguimiento: notas, tareas y alertas hasta lograr el objetivo.","Cierre: verificar pendientes, justificar y enviar a revisión."]'::jsonb,'[]'::jsonb,true),

(NULL,'Guía de competencia estatal y municipal','State and municipal competence guidance',
 'Cómo identificar la autoridad competente según el estado y municipio de la persona usuaria.',
 'How to identify the competent authority based on the client''s state and municipality.',
 'Los servicios de protección de niñez, atención a víctimas y refugios operan por competencia estatal; migración y refugio son federales. Confirme siempre la oficina con cobertura en el municipio de la persona antes de canalizar y registre la delegación o sede exacta.',
 'Child protection, victim assistance and shelters operate at state level; migration and asylum are federal. Always confirm the office covering the client''s municipality before referring, and record the exact branch.',
 'state_municipal_guidance',ARRAY['state_guidance','referrals','case_management'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Evitar canalizaciones a instancias sin competencia territorial.','Antes de crear cualquier canalización local.',ARRAY['case_management'],
 '["Confirmar estado y municipio actuales de la persona usuaria.","Determinar si la materia es federal o estatal.","Buscar la sede con cobertura en la Red de Recursos.","Verificar horario y requisitos de atención presencial.","Registrar la sede exacta en la canalización."]'::jsonb,'[]'::jsonb,true),

(NULL,'Formatos y listas de verificación aprobados','Approved forms and checklists',
 'Contenido mínimo de los formatos de recepción, consentimiento, canalización y cierre.',
 'Minimum content for intake, consent, referral and closure forms.',
 'Formato de recepción: identidad, contacto, composición familiar, necesidades, riesgo inicial. Consentimiento: finalidad, destinatarios, información autorizada, vigencia, firma. Canalización: servicio solicitado, motivo, urgencia, información autorizada. Cierre: objetivos alcanzados, pendientes, motivo y revisión.',
 'Intake form: identity, contact, household, needs, initial risk. Consent: purpose, recipients, authorized information, validity, signature. Referral: service requested, reason, urgency, authorized information. Closure: goals achieved, pending items, reason and review.',
 'document_checklist',ARRAY['forms_templates','case_management','consent_privacy'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Asegurar expedientes completos y auditables.','Al abrir, canalizar o cerrar un caso.',ARRAY['case_management'],
 '["Usar el formato correspondiente a la etapa del caso.","Verificar que no existan campos obligatorios vacíos.","Adjuntar el documento al expediente del caso.","Registrar la versión del formato utilizada."]'::jsonb,'[]'::jsonb,true),

(NULL,'Capacitación básica del personal de atención integral','Core comprehensive care staff training',
 'Contenidos mínimos de inducción: enfoque de derechos, atención sin daño y límites profesionales.',
 'Minimum induction content: rights-based approach, do-no-harm practice and professional boundaries.',
 'La atención se brinda con enfoque de derechos humanos, perspectiva de género, interés superior de la niñez y atención sin daño. El personal no clínico no diagnostica y el personal no jurídico no asesora sobre el fondo legal. Toda persona usuaria puede negarse a un servicio sin perder el acceso a otros.',
 'Care is delivered with a human rights approach, gender perspective, best interests of the child and do-no-harm practice. Non-clinical staff do not diagnose and non-legal staff do not give substantive legal advice. Clients may decline a service without losing access to others.',
 'training_material',ARRAY['training','social_work','consent_privacy'],'{}',ARRAY['nyrava_approved_library'],'Nyrava México','','published',now(),date '2026-01-01',now(),now()+interval '12 months','internal_staff',ARRAY['es','en'],
 'Establecer la base común de práctica profesional.','Durante la inducción y en la revisión anual del personal.',ARRAY['training'],
 '["Revisar principios de atención y límites profesionales.","Practicar entrevista segura y registro objetivo.","Revisar rutas de escalamiento de riesgo.","Confirmar comprensión y registrar la capacitación."]'::jsonb,'[]'::jsonb,true),

(NULL,'Actualizaciones normativas relevantes para atención integral','Regulatory updates relevant to comprehensive care',
 'Marco vigente aplicable a la operación de atención integral y control de cambios.',
 'Current framework applicable to comprehensive care operations and change control.',
 'Marco base: Ley sobre Refugiados, Protección Complementaria y Asilo Político; Ley de Migración; Ley General de los Derechos de Niñas, Niños y Adolescentes; Ley General de Acceso de las Mujeres a una Vida Libre de Violencia; Ley General de Víctimas; LFPDPPP. Cualquier cambio normativo debe verificarse en el DOF antes de modificar un procedimiento aprobado.',
 'Baseline framework: Refugee, Complementary Protection and Political Asylum Act; Migration Act; General Act on the Rights of Children and Adolescents; General Act on Women''s Access to a Life Free of Violence; General Victims Act; Federal Data Protection Act. Any regulatory change must be verified in the official gazette before amending an approved procedure.',
 'legal_update',ARRAY['legal_updates','legal_services','consent_privacy'],'{}',ARRAY['nyrava_approved_library'],'Diario Oficial de la Federación','https://www.dof.gob.mx','published',now(),date '2026-01-01',now(),now()+interval '6 months','internal_staff',ARRAY['es','en'],
 'Mantener los procedimientos alineados al marco vigente.','Al revisar procedimientos o ante aviso de reforma legal.',ARRAY['compliance'],
 '["Verificar la publicación en el DOF y su fecha de entrada en vigor.","Identificar los procedimientos afectados.","Enviar la propuesta de actualización a revisión.","Publicar la nueva versión y archivar la anterior."]'::jsonb,
 '[{"title":"Diario Oficial de la Federación","url":"https://www.dof.gob.mx"}]'::jsonb,true);